### ISSUE TITLE
There is a problem connecting the principled shader here.

### ISSUE THREAD

**Issue by Dayar886** [ugorek000/VoronoiLinker#11]
<img width="790" alt="Snipaste_2023-05-29_17-08-47" src="https://github.com/ugorek000/VoronoiLinker/assets/49119849/ef414559-7a04-469e-8899-7797d43be96f">

**Comment by Dayar886** [comment]
The pointer points to "random walk", but the connection is indeed the "base color" below

**Comment by Dayar886** [comment]
https://github.com/ugorek000/VoronoiLinker/assets/49119849/6217f598-40a8-476e-8f59-482dc2b91dfc

**Comment by ugorek000** [comment]
I don't have any ideas. Somewhere there is an excess offset. Can you provide a .blend file?

**Comment by NewTypo** [comment]
朋友，我也遇到了同样的问题。
Друг, у меня тоже была такая же проблема

[螺母.zip](https://github.com/ugorek000/VoronoiLinker/files/11880908/default.zip)

**Comment by ugorek000** [comment]
Well, I understood what was the problem.
UI scale affects this. Thanks for the help.
