### ISSUE TITLE
👋🐛

### ISSUE THREAD

**Issue by NewTypo** [ugorek000/VoronoiLinker#12]
![2023-06-26_08-12](https://github.com/ugorek000/VoronoiLinker/assets/17538796/a1787d60-47b7-4c9b-a9fc-53e1215e478b)

在 _纹理坐标_ 节点上 `ALT+S` 报错。
Сообщение об ошибке в узле координат текстуры 'ALT+S'.

谢谢你和你优秀的插件。
Спасибо вам и вашему отличному плагину.

**Comment by ugorek000** [comment]
Thanks, fixed.
