### ISSUE TITLE
Can live preview support collapsed nodes

### ISSUE THREAD

**Issue by chenpaner** [ugorek000/VoronoiLinker#13]
1、Can live preview support collapsed nodes？
![动画1](https://github.com/ugorek000/VoronoiLinker/assets/107256886/cd8e9538-3b1b-4e89-8688-dcfe5e6b8a84)

2、Can it support switching output ports?
![动画2](https://github.com/ugorek000/VoronoiLinker/assets/107256886/d4b3e859-54bc-4190-b9ec-03ad5b2470d3)

**Comment by ugorek000** [comment]
1. Maybe, but I'm too lazy to support collapsed nodes for all tools.
2. I added the ability to press space or shift and reselect the output socket (which is also a quick crutch without competent implementation).

**Comment by chenpaner** [comment]
I tried to fix the "live preview support collapsed nodes" issue. It seems to work without any errors in my own tests. 

class VoronoiPreviewer(bpy.types.Operator, VoronoiOpBase):
    def NextAssessment(self, context):
         ..................
        # if (nd.hide)and(nd.type!='REROUTE'):# Disable this line
        #     continue  # Disable this line
        CrutchWithCollapseNode(nd, 'In')  # Add this line
        ..................

    def modal(self, context, event):
        ..................
        if (not self.dict_isAllToRelease) or (event.type == 'ESC'):
            bpy.types.SpaceNodeEditor.draw_handler_remove(self.handle, 'WINDOW')
            if not context.space_data.edit_tree:
                return {'FINISHED'}
            CrutchWithCollapseNode(None, 'In', True)  # Add this line
            CrutchWithCollapseNode(None, 'Out', True)  # Add this line
            if self.foundGoalSkOut:
           ..................
Please take a look to see if it's correct.

**Comment by chenpaner** [comment]
There is another issue that arises when uninstalling the plugin:
Traceback (most recent call last):
  File "G:\Blender Program\stable\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 421, in disable
    mod.unregister()
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\VoronoiLinker.py", line 2014, in unregister
    globalVars.keyMapNodeEditor.keymap_items.remove(kmi)
NameError: name 'kmi' is not defined

 I also attempted to fix it.

kmi = None ## # # # #  Add this line
voronoiAnchorName = "Voronoi_Anchor"
voronoiSkPreviewName = "voronoi_preview"
............
............
def register():
    global kmi # # # # # Add this line
    for ti in tuple_classes:
        bpy.utils.register_class(ti)
    ............
    ............
def unregister():
    global kmi # # # # # Add this line
    for ti in reversed(tuple_classes):
        bpy.utils.unregister_class(ti)
    for li in list_addonKeymaps:
        if li.idname in globalVars.keyMapNodeEditor.keymap_items: ## # # # #  Add this line
            globalVars.keyMapNodeEditor.keymap_items.remove(li)
    list_addonKeymaps.clear()
    for li in list_helpClasses:
        li.unregister()

**Comment by ugorek000** [comment]
Regarding the uninstalling error, I forgot to replace `kmi` with `li` in the `unregister()` function.
