### ISSUE TITLE
Can I using Fast Math Pie contain switch、mix、compare node？

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#14]
Hey, author.I really like this plugin.Can I use a pie menu that includes switch, compare, and mix for the math socket while using Fast Math Pie? Or is it that I didn't set it right. They are all very useful. Thank you very much.
https://github.com/ugorek000/VoronoiLinker/assets/98995559/fb50fa08-566c-4c19-84e2-0cd0e3c3ab42

**Comment by ugorek000** [comment]
Fast math is exclusively for fast math. Adding other nodes there will be nothing more than a crutch. I'll think about what can be done about it.

**Comment by ugorek000** [comment]
Придумал. Скоро будет.
