### ISSUE TITLE
Can we directly change the colors of "VoronoiEnumSelector" and "SocketArea" in the preferences settings?

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#15]
I really like your update, I can't do without this plugin anymore.
A small optimization suggestion.I hope this won't disturb you.
Can we directly change the colors of "VoronoiEnumSelector" and "SocketArea" in the preferences settings?
It behaves normally in the Dark theme, but strangely in the White theme. Although changes can be found in the plugin code, it is not convenient for people who do not understand the code to make changes.
What do you think?

![VoronoiEnumSelector and SocketArea](https://github.com/ugorek000/VoronoiLinker/assets/98995559/66dbddee-6f92-40f9-a263-eccda099bee9)
![image](https://github.com/ugorek000/VoronoiLinker/assets/98995559/ba4411ed-fa3f-492e-b416-2568347ffc96)

**Comment by ugorek000** [comment]
Thanks, added.

**Comment by ugorek000** [comment]
What text editor do you use?

**Comment by yunkezengren** [comment]
I'm using VS code.
