### ISSUE TITLE
Reroutes with strange move.

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#16]
The use of lazy links or hidden sockets in plugins can cause strange move of reroutes in some simulation/repeat zones (it is currently unclear whether reroutes outside the zone will be affected). I hope you can understand what I mean.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/7b2e68ba-07db-40fa-aab5-d4323c3a2b44

**Comment by ugorek000** [comment]
Very strange. I have no idea why this happens. Can you provide the .blend file?

**Comment by yunkezengren** [comment]
[Reroutes with strange move.zip](https://github.com/ugorek000/VoronoiLinker/files/12640228/Reroutes.with.strange.move.zip)
The 4.0 file is my own. Someone sent me another file (he didn't install VoronoiLinker)

**Comment by ugorek000** [comment]
Oh my God. I was able to reproduce the problem. Very strange. I'll fix it soon. Thanks for the report.

**Comment by ugorek000** [comment]
The reason has been established. This happens because the redirect is hidden.

**Comment by yunkezengren** [comment]
That's great. I'm glad it was resolved so quickly.🎉
