### ISSUE TITLE
Alt Rightclick fromVirtual socket to other socket report error

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#19]
1. Add-on 3.5.3 is normal, but several versions will report errors afterwards, and 3.6.0 will report errors also. Is this my own problem?
![image](https://github.com/ugorek000/VoronoiLinker/assets/98995559/5e3366b9-a6ba-430b-9595-0fc36bb1aa51)

2.This is a small suggestion or inquiry below. What do you think of the fast switching of Group Input node and Node Group node?

![image](https://github.com/ugorek000/VoronoiLinker/assets/98995559/3364611f-67ca-4cea-bab0-3c576b68b6ce)

3.There is another small request. Can you provide some detailed introduction to the new features. I really like your new feature, but sometimes it takes some effort to understand what's useful and how to use it.

I really like your Add-on.

**Comment by ugorek000** [comment]
1. I can't reproduce this. Most likely there is no check for NoneType. I had no idea that `material.node_tree` could be None.

2. An interesting idea, but quite specific. For these purposes, some other addon is already more suitable.
Besides, at this rate, there won't be enough hotkeys for everything.
And you also need to have two options where they swap places, and where one moves to a new place with the shift of all others (which in the case of VL will be too inconvenient to handle extreme cases.)

I'll see what I can do about it. I liked this idea.

3. Sooner or later I will make a new wiki with descriptions of all tools and all them features. But for this i need to spend a lot of energy and time, at the moment I'm too lazy. I will wait for the arrival of popularity for this.
