### ISSUE TITLE
Quick menu bug

### ISSUE THREAD

**Issue by Ledracarnos** [ugorek000/VoronoiLinker#20]
If I press a key while my mouse hovers over a menu item it spawns two nodes
![bug](https://github.com/ugorek000/VoronoiLinker/assets/79541759/0f88cc64-6d09-439d-a165-3f4fd6151dd6)

**Comment by ugorek000** [comment]
O:

**Comment by ugorek000** [comment]
https://projects.blender.org/blender/blender/issues/115155
