### ISSUE TITLE
Line Width does not modify with Zoom Level

### ISSUE THREAD

**Issue by Tams3d** [ugorek000/VoronoiLinker#22]
![Screenshot 2023-12-15 191000](https://github.com/ugorek000/VoronoiLinker/assets/106262964/197bf86e-2372-425a-8c78-67ead5244f10)

# Issue
- When using many nodes in the NodeTree, it is natural to Zoom Out and Zoom In. The Line width remains as constant and does not adapt to the Zoom Level Changes
- The line width must be divided with the current zoom level. This may also applicable for the Point Size

**Comment by ugorek000** [comment]
Unfortunately, the line thickness was not intended to be dependent on the editor's scale. Maybe someday in the future I will add it.
