### ISSUE TITLE
Voronoi Preview always link a fixed preview node, even if it is inactive.

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#24]
https://github.com/ugorek000/VoronoiLinker/assets/98995559/dcf4c403-b6c7-4753-833b-b127a98be795

This is a bit strange.
I have tried the latest version of plugins and Blender 3.6 and 4.1.They are all like this.
I often place some viewer nodes in the node tree to remind myself of something.
I remember in the past, Voronoi Preview would be connected to the active viewer node.
What do you think？

**Comment by ugorek000** [comment]
Blender does not have an api for viewers.
There is no way to determine which one is active.
https://blender.stackexchange.com/questions/291084/how-to-find-out-if-geonodess-viewer-is-active
The main purpose of the viewer is to be a mobile override viewer. So when there is only one, it is quite comfortable to work with him and VL. In addition, his concept seems to mean that he will not be a permanent participant in the tree, but is only needed temporarily while the tree is being built. In addition, given the large number of VL tools, there are no convenient hotkeys left to specify the output of group or viewer.

**Comment by yunkezengren** [comment]
@ugorek000 
I consulted a person and found the name of the active Viewer node based on the ideas he provided.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/47a49c12-a0ef-449a-a98d-862a330eb670

```python
import bpy
# viewer_path.path[-1].node_name   # 3.6
# viewer_path.path[-1].ui_name     # 4.1

for area in bpy.context.screen.areas:
    if area.type == "SPREADSHEET":
        view_name = area.spaces[0].viewer_path.path[-1].ui_name
```

**Comment by ugorek000** [comment]
Cool of course, but... if the only way to get a weaver's name is to have an area spreadsheet, then this method is not suitable at all. Otherwise, there will be a lot of crutches again.

This need is not that common, and VL has other more serious problems than that. Then, in the distant future, I will think about what can be done about it. It will be much easier to wait for the api than to rack your brains.

**Comment by yunkezengren** [comment]
Thank you for your patient reply.Thank you for your plugin.
I added a condition in the code myself to find the active Viewer when there is a spreadsheet, and to keep it as default when there is none.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/b999d0e9-3444-41c5-8bac-5ecc8a7be2a6

**Comment by ugorek000** [comment]
Well... I'll probably make a separate option for that. Thanks for your bug reports.
