### ISSUE TITLE
这是一个我已经离不开的插件，他会上传到blender官方市场默认。

### ISSUE THREAD

**Issue by NewTypo** [ugorek000/VoronoiLinker#30]
这个插件简直太棒了，如标题所说他会上架到blender市场么(https://extensions.blender.org )。

**Comment by neliut** [comment]
"This is the plugin I can't live without" 😄
I first learned about the extensions.blender.org, at first glance it looks cool. But, now, I don’t have any special motivation for this. I would like to polish the VL to perfection, and then I can think about it.

**Comment by neliut** [comment]
[terms-of-service](https://extensions.blender.org/terms-of-service/#:~:text=documented%20and%20actively)
![image](https://github.com/ugorek000/VoronoiLinker/assets/120259754/d0a3e2e9-c7dd-4a4b-906c-085ac10f1c5b)
